2025-05-12 18:17:18,606 [PID 54575] DEBUG Using selector: KqueueSelector
2025-05-12 18:17:18,608 [PID 54575] INFO Reading Pyre server configurations...
2025-05-12 18:17:18,611 [PID 54575] ERROR Uncaught error in persistent.run
Traceback (most recent call last):
  File "/Users/habidi2021/.local/share/nvim/mason/packages/pyre/venv/lib/python3.9/site-packages/pyre_check/client/commands/persistent.py", line 302, in run
    return asyncio.get_event_loop().run_until_complete(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/habidi2021/.local/share/nvim/mason/packages/pyre/venv/lib/python3.9/site-packages/pyre_check/client/commands/persistent.py", line 225, in run_persistent
    initial_server_options = pyre_server_options.read_server_options(
  File "/Users/habidi2021/.local/share/nvim/mason/packages/pyre/venv/lib/python3.9/site-packages/pyre_check/client/commands/pyre_server_options.py", line 130, in read_server_options
    return server_options_reader()
  File "/Users/habidi2021/.local/share/nvim/mason/packages/pyre/venv/lib/python3.9/site-packages/pyre_check/client/commands/pyre_server_options.py", line 115, in read
    return PyreServerOptions.create(
  File "/Users/habidi2021/.local/share/nvim/mason/packages/pyre/venv/lib/python3.9/site-packages/pyre_check/client/commands/pyre_server_options.py", line 95, in create
    start_arguments = start.create_server_arguments(
  File "/Users/habidi2021/.local/share/nvim/mason/packages/pyre/venv/lib/python3.9/site-packages/pyre_check/client/commands/start.py", line 316, in create_server_arguments
    source_paths = backend_arguments.get_source_path_for_server(
  File "/Users/habidi2021/.local/share/nvim/mason/packages/pyre/venv/lib/python3.9/site-packages/pyre_check/client/backend_arguments.py", line 398, in get_source_path_for_server
    return get_source_path(configuration, artifact_root_name, flavor, watchman_root)
  File "/Users/habidi2021/.local/share/nvim/mason/packages/pyre/venv/lib/python3.9/site-packages/pyre_check/client/backend_arguments.py", line 379, in get_source_path
    raise configuration_module.InvalidConfiguration(
pyre_check.client.configuration.exceptions.InvalidConfiguration: Invalid configuration: Cannot find any source files to analyze. Either `source_directories` or `targets` must be specified.
